version: '3'
services:
  # JMeter Service for running the test
  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    volumes:
      - ./scripts/test_plan.jmx:/tests/test_plan.jmx  # Adjust the host path accordingly
    command: -n -t /tests/test_plan.jmx -l /results/results.jtl -j /results/jmeter.log
    networks:
      - backend
    depends_on:
      - nginx  # Ensure Nginx is up before running the test

  # Prometheus for monitoring the metrics
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your Prometheus config
    ports:
      - "9090:9090"
    networks:
      - backend

  # Nginx Service as the reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx configuration
    networks:
      - backend

  # Grafana for visualizing metrics from Prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend

networks:
  backend:
    driver: bridge